My branch
AramLab/todo-list pull request #1
Opened 2024-08-05 18:47 UTC by AramLab

2024-08-06 14:25 UTC, dirtymew requested changes
Привет Арам

Дал комментарии что поправить и улучшить, для первой итерации думаю достаточно

нужно еще добавить в документацию как запустить/настроить и протестировать приложение

задания со звездочкой делать будешь?

2024-08-06 14:25 UTC, dirtymew commented on utils/validator.go
> +func ValidateTitle(title string) error {
мб лучше сделать методами структуры Task?

2024-08-06 14:25 UTC, dirtymew commented on utils/task_repeater.go
> +	taskDate, err := time.Parse("20060102", date)
20060102 в константу и везде использовать

2024-08-06 14:25 UTC, dirtymew commented on utils/getTask.go
> +package utils
utils - считается плохим названием и плохой практикой

тут я бы рекомендовал сделать пакет storage - посмотри пример в задании про посылки и все методы по работе с бд сделать там

2024-08-06 14:25 UTC, dirtymew commented on types/types.go
> +package types
лучше models или вообще по другим пакетам разнести

2024-08-06 14:25 UTC, dirtymew commented on utils/getTask.go
> +	} else if err != nil {
лучше не используй эту конструкцию - код очень плохо читаемы становиться

просто несколько if читаются проще

2024-08-06 14:25 UTC, dirtymew commented on utils/getTasks.go
> +	rows, err := db.Query("SELECT id, date, title, comment, repeat FROM scheduler ORDER BY date ASC LIMIT 50")
лимит в константу вынеси

2024-08-06 14:25 UTC, dirtymew commented on main.go
> +	appPath, err := os.Executable()
лучше использовать относительный путь - мб os.Getwd

2024-08-06 14:25 UTC, dirtymew commented on main.go
> +		log.Println("ошибка запуска сервера")
а зачем 2 лога ?  одного будет достаточно

2024-08-06 14:25 UTC, dirtymew commented on handlers/handlers.go
> +
что-то с импортами в проекте -нужно везде поправить

они должны быть сгруппированы и отсортированы

используй go imports

2024-08-06 14:25 UTC, dirtymew commented on handlers/handlers.go
> +	res, err := h.DB.Exec(`INSERT INTO scheduler (date, title, comment, repeat) VALUES (?, ?, ?, ?)`,
у тебе функционал разьехался по пакетам - и в целом перегруженны логикой хендлеры

посмотри как компоненты сделаны в задании про посылки 
и еше вот в помощь статья по архитектуре https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10

пусть хендлеры только своим делом занимаются - обрабатывают http запросы и ответы
остальную логику реализуй в других пакетах

2024-08-06 14:25 UTC, dirtymew commented on handlers/handlers.go
> +/*func (h *Handlers) AddTaskHandler(w http.ResponseWriter, r *http.Request) {
лишнее нужно убирать

2024-08-06 14:25 UTC, dirtymew commented on handlers/handlers.go
> +	w.Write(jsonResponse)
_ , _ = w.Write(resp)

тут нужно либо явно проигнорировать ошибку или ее логировать

хорошие линтеры на это ругаться будут и не зря

2024-08-08 16:54 UTC, AramLab commented on handlers/handlers.go
> +	res, err := h.DB.Exec(`INSERT INTO scheduler (date, title, comment, repeat) VALUES (?, ?, ?, ?)`,
Я попробовал, но не смог связать. Не подскажите, может есть другие источники, где написано более простым языком?

2024-08-09 10:36 UTC, dirtymew commented on handlers/handlers.go
> +	res, err := h.DB.Exec(`INSERT INTO scheduler (date, title, comment, repeat) VALUES (?, ?, ?, ?)`,
@AramLab это сложная тема - статья довольно простая, но если есть сложности то нужно потихоньку изучать

https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html

мб книги по дизайну софта - ну и гуглить по "Чистая архитектура" и "MVP" (model-view-controller)

на youtube полно всего на этот счет и можно даже найти и на GO

2024-08-09 12:02 UTC, dirtymew approved these changes
Привет Арам

на вопрос про задания со звездочкой ответа не получил - поэтому ждать их не буду

по базовому заданию вопросов нет - все отлично

Поздравляю и желаю удачи

2024-08-09 12:02 UTC, dirtymew commented on main.go
> +		install = true
сразу бы и database.CreateDatabase(db)

2024-08-09 12:02 UTC, dirtymew commented on main.go
> +		install = true
лишняя переменная

2024-08-09 12:02 UTC, dirtymew commented on handlers/handlers.go
> +	task, err := storage.GetTask(id, h.DB)
к вопросу об архитектуре 

вот тут можно почувствовать этот момент

когда уже хенжлер перестает своим делом заниматься - а в нем какая-то логика начинает присутсвовать

тут помог бы еще один уровень абстракции - service....

2024-08-11 00:18 UTC, closed without merging